# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "e129cba7-285d-40a8-8173-d5a3446b692c"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build the release variant
  build_android_app(task: "assembleRelease")

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "72caf1ef03644747d6e011ea1e7a2aac4dbcda43",
    build_secret: "98af9350e846143ff1797029be8661e5e0ddb439d1fecc930ee3db29b590b204"
  )
end
